server:
  port: 8080 # TODO: change to the appropriate port (not needed for kubernetes deployments)
  error:
    include-stacktrace: never # Should be set to "never" in production environments. Unfortunately "on_trace_param" does not work with the Problem library, so we just ignore it.
  servlet:
    context-path: # TODO: change to the appropriate context path, if required (not needed for kubernetes deployments)

logging:
  path: /var/log/${project.name}
  level:
    uk.co.agilesoftware: info
    reactor.netty.http.client: error
    io.netty: error
    reactor.core.publisher.Operators: error

upstream:
  user-agent-header: platform-agent/ares
  client:
    lexicon:
      connect-timeout-seconds: 3
      read-write-timeout-seconds: 6
      max-connection-idle-seconds: 90
      max-in-memory-buffer-mb: 10
      enable-micrometer-metric: false
      resources:
        cinemaworld:
          max-connections: 200
        filmworld:
          max-connections: 200
