logging:
  path: target
  level:
    uk.co.agilesoftware: debug

upstream:
  client:
    lexicon:
      api-key: Yr2636E6BTD3UCdleMkf7UEdqKnd9n361TQL9An7 # this should ideally come from a secrets manager
      endpoint: https://challenge.lexicondigital.com.au/api/v2
